
version: "3"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - redis:/data
  admin:
    build:
      context: ./packages/admin
    image: nextjs_admin
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=http://api:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - my-network
    volumes:
      - ./packages/admin:/app
      - ./node_modules:/app/node_modules
    command: yarn dev
  api:
    build:
      context: ./packages/api
    image: nestjs-api
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    networks:
      - my-network
    volumes:
      - ./packages/api:/app
      - ./node_modules:/app/node_modules
    command: yarn start:dev

volumes:
  postgres:
    name: postgres
  redis:
    name: redis
networks:
  my-network:
    driver: bridge